vssr更新

diff --git a/luci-app-vssr-plus/root/usr/bin/vssr-rules b/luci-app-vssr-plus/root/usr/bin/vssr-rules
--- a/luci-app-vssr-plus/root/usr/bin/vssr-rules
+++ b/luci-app-vssr-plus/root/usr/bin/vssr-rules
@@ -126,25 +126,25 @@ ipset_r() {
 }
 
 fw_rule() {
-	$IPT -N SS_SPEC_WAN_FW
-	$IPT -A SS_SPEC_WAN_FW -d 0.0.0.0/8 -j RETURN
-	$IPT -A SS_SPEC_WAN_FW -d 10.0.0.0/8 -j RETURN
-	$IPT -A SS_SPEC_WAN_FW -d 127.0.0.0/8 -j RETURN
-	$IPT -A SS_SPEC_WAN_FW -d 169.254.0.0/16 -j RETURN
-	$IPT -A SS_SPEC_WAN_FW -d 172.16.0.0/12 -j RETURN
-	$IPT -A SS_SPEC_WAN_FW -d 192.168.0.0/16 -j RETURN
-	$IPT -A SS_SPEC_WAN_FW -d 224.0.0.0/4 -j RETURN
-	$IPT -A SS_SPEC_WAN_FW -d 240.0.0.0/4 -j RETURN
-	$IPT -A SS_SPEC_WAN_FW -p tcp $PROXY_PORTS \
-	-j REDIRECT --to-ports $local_port 2>/dev/null || {
-		loger 3 "Can't redirect, please check the iptables."
-		exit 1
-	}
-	return $?
+	    $IPT -N SS_SPEC_WAN_FW
+	    $IPT -A SS_SPEC_WAN_FW -d 0.0.0.0/8 -j RETURN
+	    $IPT -A SS_SPEC_WAN_FW -d 10.0.0.0/8 -j RETURN
+	    $IPT -A SS_SPEC_WAN_FW -d 127.0.0.0/8 -j RETURN
+	    $IPT -A SS_SPEC_WAN_FW -d 169.254.0.0/16 -j RETURN
+	    $IPT -A SS_SPEC_WAN_FW -d 172.16.0.0/12 -j RETURN
+	    $IPT -A SS_SPEC_WAN_FW -d 192.168.0.0/16 -j RETURN
+	    $IPT -A SS_SPEC_WAN_FW -d 224.0.0.0/4 -j RETURN
+	    $IPT -A SS_SPEC_WAN_FW -d 240.0.0.0/4 -j RETURN
+	    $IPT -A SS_SPEC_WAN_FW -p tcp $PROXY_PORTS \
+	            -j REDIRECT --to-ports $local_port 2>/dev/null || {
+		        loger 3 "Can't redirect, please check the iptables."
+		        exit 1
+	    }
+	    return $?
 }
 
 ac_rule() {
-	if [ -n "$LAN_AC_IP" ]; then
+	    if [ -n "$LAN_AC_IP" ]; then
 		case "${LAN_AC_IP:0:1}" in
 		w | W)
 			MATCH_SET="-m set --match-set ss_spec_lan_ac src"
@@ -182,26 +182,26 @@ ac_rule() {
 }
 
 tp_rule() {
-	[ -n "$TPROXY" ] || return 0
-	ip rule add fwmark 0x01/0x01 table 100
-	ip route add local 0.0.0.0/0 dev lo table 100
-	local ipt="iptables -t mangle"
-	$ipt -N SS_SPEC_TPROXY
-	$ipt -A SS_SPEC_TPROXY -p udp --dport 443 -j DROP
-	$ipt -A SS_SPEC_TPROXY -p udp --dport 53 -j RETURN
-	$ipt -A SS_SPEC_TPROXY -p udp -d 0.0.0.0/8 -j RETURN
-	$ipt -A SS_SPEC_TPROXY -p udp -d 10.0.0.0/8 -j RETURN
-	$ipt -A SS_SPEC_TPROXY -p udp -d 127.0.0.0/8 -j RETURN
-	$ipt -A SS_SPEC_TPROXY -p udp -d 169.254.0.0/16 -j RETURN
-	$ipt -A SS_SPEC_TPROXY -p udp -d 172.16.0.0/12 -j RETURN
-	$ipt -A SS_SPEC_TPROXY -p udp -d 192.168.0.0/16 -j RETURN
-	$ipt -A SS_SPEC_TPROXY -p udp -d 224.0.0.0/4 -j RETURN
-	$ipt -A SS_SPEC_TPROXY -p udp -d 240.0.0.0/4 -j RETURN
-	$ipt -A SS_SPEC_TPROXY -p udp ! --dport 53 -d $server -j RETURN
-	$ipt -A SS_SPEC_TPROXY -p udp -m set --match-set bplan src -j RETURN
+	    [ -n "$TPROXY" ] || return 0
+	    ip rule add fwmark 0x01/0x01 table 100
+	    ip route add local 0.0.0.0/0 dev lo table 100
+	    local ipt="iptables -t mangle"
+	    $ipt -N SS_SPEC_TPROXY
+	    $ipt -A SS_SPEC_TPROXY -p udp --dport 443 -j DROP
+	    $ipt -A SS_SPEC_TPROXY -p udp --dport 53 -j RETURN
+	    $ipt -A SS_SPEC_TPROXY -p udp -d 0.0.0.0/8 -j RETURN
+	    $ipt -A SS_SPEC_TPROXY -p udp -d 10.0.0.0/8 -j RETURN
+	    $ipt -A SS_SPEC_TPROXY -p udp -d 127.0.0.0/8 -j RETURN
+	    $ipt -A SS_SPEC_TPROXY -p udp -d 169.254.0.0/16 -j RETURN
+	    $ipt -A SS_SPEC_TPROXY -p udp -d 172.16.0.0/12 -j RETURN
+	    $ipt -A SS_SPEC_TPROXY -p udp -d 192.168.0.0/16 -j RETURN
+	    $ipt -A SS_SPEC_TPROXY -p udp -d 224.0.0.0/4 -j RETURN
+	    $ipt -A SS_SPEC_TPROXY -p udp -d 240.0.0.0/4 -j RETURN
+	    $ipt -A SS_SPEC_TPROXY -p udp ! --dport 53 -d $server -j RETURN
+	    $ipt -A SS_SPEC_TPROXY -p udp -m set --match-set bplan src -j RETURN
 	$ipt -A SS_SPEC_TPROXY -p udp $PROXY_PORTS -m set --match-set fplan src \
-	-j TPROXY --on-port "$LOCAL_PORT" --tproxy-mark 0x01/0x01
-	if [ "$RUNMODE" == "router" ]; then
+	              -j TPROXY --on-port "$LOCAL_PORT" --tproxy-mark 0x01/0x01
+	    if [ "$RUNMODE" == "router" ]; then
 		$ipt -A SS_SPEC_TPROXY -p udp -m set --match-set gmlan src -m set ! --match-set china dst \
 		-j TPROXY --on-port "$LOCAL_PORT" --tproxy-mark 0x01/0x01
 		$ipt -A SS_SPEC_TPROXY -p udp $PROXY_PORTS -m set ! --match-set ss_spec_wan_ac dst \
